[package]
name = "rsocket-proto"
version = "0.1.0"
description = "RSocket Protocol Implementation"
keywords = ["rsocket", "net", "protocol"]
edition = "2021"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]
repository = "https://github.com/real-evolution/rsocket-proto"
license-file = "LICENSE"
readme = true
publish = true

[dependencies]
thiserror = { version = "1" }
